//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace certcheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("certcheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Initial Check Failed.
        /// </summary>
        internal static string EmailInitialCheckSubject {
            get {
                return ResourceManager.GetString("EmailInitialCheckSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate in file {0}  is classified as not valid during the initial certificate check because of the following: {1}
        ///
        ///The file was moved to {2}..
        /// </summary>
        internal static string EmailInitialCheckTemplate {
            get {
                return ResourceManager.GetString("EmailInitialCheckTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Regular Check Failed.
        /// </summary>
        internal static string EmailRegularCheckSubject {
            get {
                return ResourceManager.GetString("EmailRegularCheckSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate in file {0}  is classified as not valid during the initial certificate check because of the following: {1}
        ///
        ///The file was moved to {2}..
        /// </summary>
        internal static string EmailRegularCheckTemplate {
            get {
                return ResourceManager.GetString("EmailRegularCheckTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is expired.
        /// </summary>
        internal static string ErrorReasonExpired {
            get {
                return ResourceManager.GetString("ErrorReasonExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HTTP status code {0}.
        /// </summary>
        internal static string ErrorReasonInvalideStatusCode {
            get {
                return ResourceManager.GetString("ErrorReasonInvalideStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTSP is not valid.
        /// </summary>
        internal static string ErrorReasonInvalidQTSP {
            get {
                return ResourceManager.GetString("ErrorReasonInvalidQTSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid signature.
        /// </summary>
        internal static string ErrorReasonInvalidSignature {
            get {
                return ResourceManager.GetString("ErrorReasonInvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is revoked.
        /// </summary>
        internal static string ErrorReasonRevoked {
            get {
                return ResourceManager.GetString("ErrorReasonRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error: {0}.
        /// </summary>
        internal static string FatalErrorHeader {
            get {
                return ResourceManager.GetString("FatalErrorHeader", resourceCulture);
            }
        }
    }
}
